package dev.detekt.rules.coroutines

import dev.detekt.api.Config
import dev.detekt.api.Entity
import dev.detekt.api.Finding
import dev.detekt.api.RequiresAnalysisApi
import dev.detekt.api.Rule
import dev.detekt.psi.hasAnnotation
import org.jetbrains.kotlin.analysis.api.KaContextParameterApi
import org.jetbrains.kotlin.analysis.api.KaSession
import org.jetbrains.kotlin.analysis.api.analyze
import org.jetbrains.kotlin.analysis.api.components.allSupertypes
import org.jetbrains.kotlin.analysis.api.symbols.KaClassSymbol
import org.jetbrains.kotlin.analysis.api.symbols.KaJavaFieldSymbol
import org.jetbrains.kotlin.analysis.api.symbols.KaPropertySymbol
import org.jetbrains.kotlin.analysis.api.symbols.KaVariableSymbol
import org.jetbrains.kotlin.analysis.api.symbols.symbol
import org.jetbrains.kotlin.analysis.api.types.KaType
import org.jetbrains.kotlin.analysis.api.types.symbol
import org.jetbrains.kotlin.lexer.KtTokens
import org.jetbrains.kotlin.name.ClassId
import org.jetbrains.kotlin.name.FqName
import org.jetbrains.kotlin.psi.KtClass
import org.jetbrains.kotlin.psi.KtClassOrObject
import org.jetbrains.kotlin.psi.KtConstructor
import org.jetbrains.kotlin.psi.KtElement
import org.jetbrains.kotlin.psi.KtModifierListOwner

/**
 * Custom exception classes that cannot be recreated by the coroutine stack trace recovery mechanism are reported.
 *
 * When an exception crosses a coroutine boundary, kotlinx.coroutines can recover the original stack trace by
 * creating a copy of the exception instance. A copy can only be created when
 *
 * - the exception implements `kotlin.coroutines.debug.StackTraceRecoverable` (introduced in Kotlin 2.4.20) and
 *   overrides `copyForStackTraceRecovery()`, or
 * - the exception declares no instance fields in itself or in any of its superclasses except `Throwable`, it is not
 *   an inner class, and it has a public constructor taking no arguments, only a message, only a cause, or a message
 *   and a cause. Constructors generated by the compiler are taken into account: a parameterless constructor is
 *   generated when all primary constructor parameters have default values, and `@JvmOverloads` generates overloads
 *   with trailing default parameters removed.
 *
 * Otherwise the original stack trace is lost, which is reported by this rule.
 *
 * Note that constructors which transform the message (so that the copy's message differs from the original one)
 * prevent recovery as well; this cannot be detected statically.
 *
 * See [Support for coroutine stack trace recovery](https://kotlinlang.org/docs/whatsnew2420.html#support-for-coroutine-stack-trace-recovery)
 * for more information.
 *
 * <noncompliant>
 * class NetworkException(val errorCode: Int) : RuntimeException()
 * </noncompliant>
 *
 * <compliant>
 * class NetworkException(val errorCode: Int) : RuntimeException(),
 *     StackTraceRecoverable<NetworkException> {
 *     override fun copyForStackTraceRecovery(): NetworkException = NetworkException(errorCode)
 * }
 *
 * // No fields and a public constructor taking only a message, a cause, both or no arguments
 * class TimeoutException(message: String, cause: Throwable?) : RuntimeException(message, cause)
 * </compliant>
 */
class MissingStackTraceRecoverable(config: Config) :
    Rule(
        config,
        "Exceptions that cannot be recreated by the coroutine stack trace recovery mechanism lose their original " +
            "stack trace when rethrown from another coroutine. Avoid instance fields, provide a public constructor " +
            "taking only a message, a cause, both or no arguments, or implement " +
            "`kotlin.coroutines.debug.StackTraceRecoverable`.",
    ),
    RequiresAnalysisApi {

    override fun visitClassOrObject(classOrObject: KtClassOrObject) {
        super.visitClassOrObject(classOrObject)
        val ktClass = classOrObject as? KtClass ?: return
        if (ktClass.isInterface()) return
        checkClass(ktClass)
    }

    @OptIn(KaContextParameterApi::class)
    context(_: KaSession)
    private fun KaType.isThrowableType(): Boolean = symbol?.classId in THROWABLE_CLASS_IDS

    @OptIn(KaContextParameterApi::class)
    context(_: KaSession)
    private fun KaType.isStackTraceRecoverableType(): Boolean = symbol?.classId == STACK_TRACE_RECOVERABLE_CLASS_ID

    private fun checkClass(ktClass: KtClass) {
        analyze(ktClass) {
            val classSymbol = ktClass.symbol as? KaClassSymbol ?: return@analyze
            val directSuperTypes = classSymbol.superTypes
            val transitiveSuperTypes = directSuperTypes + directSuperTypes.flatMap { it.allSupertypes }
            if (transitiveSuperTypes.none { it.isThrowableType() }) return@analyze
            if (transitiveSuperTypes.any { it.isStackTraceRecoverableType() }) return@analyze
            nonRecoverableReason(ktClass, classSymbol)?.let { reason ->
                report(Finding(Entity.atName(ktClass), reason))
            }
        }
    }

    private fun nonRecoverableReason(ktClass: KtClass, classSymbol: KaClassSymbol): String? =
        when {
            classSymbol.hasInstanceFieldsInHierarchy(ktClass) ->
                "The exception `${ktClass.name}` declares instance fields which prevent the coroutine stack trace " +
                    "recovery from copying it. Implement `kotlin.coroutines.debug.StackTraceRecoverable` and " +
                    "override `copyForStackTraceRecovery()`."

            !hasRecoverablePublicConstructor(ktClass) ->
                "The exception `${ktClass.name}` has no public constructor taking no arguments, only a message, " +
                    "only a cause, or a message and a cause, which prevents the coroutine stack trace recovery " +
                    "from copying it. Add such a constructor or implement " +
                    "`kotlin.coroutines.debug.StackTraceRecoverable`."

            else -> null
        }

    private fun KaClassSymbol.hasInstanceFieldsInHierarchy(anchor: KtElement): Boolean =
        analyze(anchor) {
            if (classId in THROWABLE_CLASS_IDS) return@analyze false
            if (hasInstanceFields(anchor)) return@analyze true
            superTypes.any { (it.symbol as? KaClassSymbol)?.hasInstanceFieldsInHierarchy(anchor) == true }
        }

    private fun KaClassSymbol.hasInstanceFields(anchor: KtElement): Boolean =
        analyze(anchor) {
            declaredMemberScope.declarations
                .filterIsInstance<KaVariableSymbol>()
                .any {
                    (it is KaJavaFieldSymbol && !it.isStatic) ||
                        (
                            it is KaPropertySymbol && !it.isStatic &&
                                (it.isDelegatedProperty || it.hasBackingField)
                            )
                }
        }

    private fun hasRecoverablePublicConstructor(ktClass: KtClass): Boolean =
        analyze(ktClass) {
            val ctorData = ktClass.explicitConstructors().map { ctor ->
                ConstructorData(
                    isPublicJvmCtor = !ctor.hasPrivateOrProtectedVisibility(),
                    hasJvmOverloads = ctor.hasAnnotation("JvmOverloads"),
                    params = ctor.valueParameters.map { param ->
                        param.typeReference?.type?.symbol?.classId to param.hasDefaultValue()
                    },
                )
            }
            when {
                ktClass.isInner() || ktClass.hasPrivateOrProtectedVisibility() -> false

                // the implicit no-arg constructor is public and takes no arguments
                ctorData.isEmpty() -> true

                else -> ctorData.any { it.isPublicJvmCtor && it.hasRecoverableSignature() }
            }
        }

    private fun KtClass.explicitConstructors(): List<KtConstructor<*>> =
        buildList {
            primaryConstructor?.let { add(it) }
            addAll(secondaryConstructors)
        }

    private fun KtModifierListOwner.hasPrivateOrProtectedVisibility(): Boolean =
        modifierList?.hasModifier(KtTokens.PRIVATE_KEYWORD) == true ||
            modifierList?.hasModifier(KtTokens.PROTECTED_KEYWORD) == true

    private class ConstructorData(
        val isPublicJvmCtor: Boolean,
        val hasJvmOverloads: Boolean,
        val params: List<Pair<ClassId?, Boolean>>,
    ) {

        fun hasRecoverableSignature(): Boolean =
            if (hasJvmOverloads) {
                // @JvmOverloads generates an overload for every trailing default parameter that is removed
                params.dropLastWhile { it.second }.map { it.first }.matchesStandardShape()
            } else {
                params.map { it.first }.matchesStandardShape() ||
                    (
                        // a parameterless constructor is generated when all parameters have default values
                        params.isNotEmpty() && params.all { it.second }
                        )
            }

        private fun List<ClassId?>.matchesStandardShape(): Boolean =
            when (size) {
                0 -> true
                1 -> this[0] in STRING_OR_THROWABLE_CLASS_IDS
                2 -> this[0] in STRING_CLASS_IDS && this[1] in THROWABLE_CLASS_IDS
                else -> false
            }
    }

    private companion object {
        val THROWABLE_CLASS_IDS = setOf(
            ClassId.topLevel(FqName("java.lang.Throwable")),
            ClassId.topLevel(FqName("kotlin.Throwable")),
        )
        val STRING_CLASS_IDS = setOf(
            ClassId.topLevel(FqName("java.lang.String")),
            ClassId.topLevel(FqName("kotlin.String")),
        )
        val STRING_OR_THROWABLE_CLASS_IDS = STRING_CLASS_IDS + THROWABLE_CLASS_IDS
        val STACK_TRACE_RECOVERABLE_CLASS_ID =
            ClassId.topLevel(FqName("kotlin.coroutines.debug.StackTraceRecoverable"))
    }
}
