processors:
  active: true
  exclude:
  # - 'KtFileCountProcessor'
  # - 'PackageCountProcessor'
  # - 'ClassCountProcessor'
  # - 'FunctionCountProcessor'
  # - 'PropertyCountProcessor'
  # - 'ProjectComplexityProcessor'
  # - 'ProjectCognitiveComplexityProcessor'
  # - 'ProjectLLOCProcessor'
  # - 'ProjectCLOCProcessor'
  # - 'ProjectLOCProcessor'
  # - 'ProjectSLOCProcessor'

potential-bugs:
  ExitOutsideMain:
    active: true
  UnnecessarySafeCall:
    active: true

style:
  ForbiddenMethodCall:
    active: true
    methods:
      - 'jvm.src.main.kotlin.Callee.forbiddenMethod'
