name: FOSSA License Scan

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  fossa-scan:
    if: github.repository == 'detekt/detekt'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Run FOSSA Scan
        uses: fossas/fossa-action@ff70fe9fe17cbd2040648f1c45e8ec4e4884dcf3 # v1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
