name: FOSSA License Scan

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  fossa-scan:
    if: github.repository == 'detekt/detekt'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Run FOSSA Scan
        uses: fossas/fossa-action@29693cc50323968e039056be419b32989fc5880c # v2
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
