name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  label-pr:
    if: github.event.sender != 'codecov' && github.repository == 'detekt/detekt'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7
        with:
          repo-token: "${{ secrets.DETEKT_CI_GITHUB_USER_TOKEN }}"
